seed_everything: true
per_run_seed: true
tags:
  exp: &exp gs_encoder_05_01
torch_hub_dir: null
huggingface_cache_dir: null
auto_resume: true
trainer:
  default_root_dir: /free/data/gsae/
  accelerator: gpu
  strategy: ddp
  devices: auto
  num_nodes: 1
  precision: bf16-mixed
  gradient_clip_val: 1.0
  gradient_clip_algorithm: norm
  logger:
      class_path: lightning.pytorch.loggers.WandbLogger
      init_args:
        project: gaussian_encoder
        name: *exp
  num_sanity_val_steps: 0
  max_steps: 600000
  val_check_interval: 5000
  check_val_every_n_epoch: null
  log_every_n_steps: 100
  deterministic: null
  inference_mode: true
  use_distributed_sampler: false
  callbacks:
    - class_path: utils.util.CheckpointHook
      init_args:
        every_n_train_steps: 5000
        save_top_k: -1
        save_last: true

model:
  ae:
    class_path: models.gaussian_ae.gs_encoder.GaussianAutoEncoder
    init_args:
      encoder_path: /home/kkkkea/.cache/dinov3
      encoder_type: dinov3
      img_size: 256
      num_gaussian: 16384
      group_size: 64
      init_random_ratio: 0.3
      init_scale: 1.0
      max_xy_shift: 4.0
      inv_scale_delta_range: 1
      rotation_delta_range: 1.0
      color_delta_scale: 1.0
      l1_loss_ratio: 1.0
      ssim_loss_ratio: 0.1
      n_head: 32
      ffn_dropout_p: 0.1
      attn_dropout_p: 0.0
      resid_dropout_p: 0.1
      norm_eps: 1e-5
      cross_layer: 6
      self_layer: 8
  ema_tracker:
    class_path: utils.util.SimpleEMA
    init_args:
      decay: 0.9999
  optimizer:
    class_path: torch.optim.AdamW
    init_args:
      lr: 2e-4
      weight_decay: 0.0
  lr_scheduler:
    class_path: torch.optim.lr_scheduler.CosineAnnealingLR
    init_args:
      T_max: 590000
      eta_min: 1e-5
  upsample_ratio: 8.0
  warmup_steps: 10000
  warmup_start_factor: 0.001
  lr_scheduler_interval: step
  lr_scheduler_frequency: 1
  enable_profiling: true
  profiling_print_freq: 1000
  profiling_warmup_steps: 100
  override_lr_on_resume: null
  override_ema_decay_on_resume: null
  enable_compile: false
data:
  train_dataset:
    class_path: dataset.aesthetic4k.Aesthetic4KDataset
    init_args:
      split: train
      lr_size: 256
      downsample_ratio: 8
  eval_dataset:
    class_path: dataset.aesthetic4k.Aesthetic4KDataset
    init_args:
      split: train
      lr_size: 256
      downsample_ratio: 8
      val_limit: 32
  pred_dataset:
    class_path: dataset.aesthetic4k.Aesthetic4KDataset
    init_args:
      split: train
      lr_size: 256
      downsample_ratio: 8
      val_limit: 32
  train_batch_size: 16
  train_num_workers: 8
  eval_batch_size: 4
  eval_num_workers: 1
  pred_batch_size: 4
  pred_num_workers: 1
